### ISSUE TITLE
Invalid POST /short-message request body example value and declaration 

### ISSUE THREAD

**Issue by arno-di-loreto** [camaraproject/ShortMessageService#15]
**Problem description**
The request body example of the POST /short-message request has 2 issues:

- The value is not valid against the `#/components/schemas/MessageRequest` JSON Schema: `to` is an array and not a string.
- The example declaration doesn't respect OpenAPI syntax. The `MessageRequest` key under `example` leads to generating an invalid example with a root `MessageRequest` property.

```yaml
example:
  MessageRequest:
    to: '+910123456789'
    from: '+919876543210'
    category: PROMOTION
    message: xxxxxxxxxx

```

**Expected behavior**
The following fixes all issues (I'll submit a PR after filling this issue). I propose using `examples` instead of `examples` (see additional context below).

```yaml
examples: # examples instead of example
  MessageRequest:
    value: # missing value field
      to: ['+910123456789'] # array instead of string
      from: '+919876543210'
      category: PROMOTION
      message: xxxxxxxxxx
```

**Additional context**

- To avoid such issues, you can use the [oas3-valid-media-example](https://github.com/stoplightio/spectral/blob/develop/docs/reference/openapi-rules.md#oas3-valid-media-example) spectral rule that allows to ensure that example values (defined via `example` or `examples`) match related JSON Schema.
- It looks like using `example` was a typo, as an example name was inside. However, just in case, I recommend using `examples` over `example` as it allows declaring multiple documented examples and connecting request/response examples (quite useful when using the OpenAPI document with Microcks). It is possible to define a spectral rule that enforces the use of `examples` over `example` (don't hesitate to ping me if you need help).
